### ISSUE TITLE
退出游戏的时候，在自动存档时报bug，生成一个

### ISSUE THREAD

**Issue by ReimsWwW** [xiaoye97/PotionCraft_AutoHaggle#2]
![image](https://github.com/user-attachments/assets/32e694e8-1706-465e-b1ff-112707a2be4b)
就用了大佬的more info 和 自动海狗灵 这俩mod，不知道具体是哪个在报错。
自动保存的存档长这样
![image](https://github.com/user-attachments/assets/07a4e9bd-7457-49d7-895c-85bceda74fdd)

**Comment by ReimsWwW** [comment]
又试了一下好像是more info导致的……

**Comment by xiaoye97** [comment]
更新更多信息到最新版本就行了
